name: scrollview_observer
description: A widget for observing data related to the child widgets being displayed in a ScrollView.
version: 2.0.0
homepage: https://github.com/fluttercandies/flutter_scrollview_observer

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  material_ui: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
