name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
      # - develop

permissions: {}

jobs:
  build:
    name: Build Web
    permissions:
      contents: write
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          # flutter-version: '3.16.9'
          channel: 'stable'
      - name: Flutter build web
        working-directory: ./example
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release --base-href /flutter_scrollview_observer/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'